on:
  push:
    branches: [ mobile-app ]

jobs:
  build:
    name: Build AAB
    runs-on: ubuntu-latest
    environment: Mobile-App
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install app dependencies
        run: npm install && npm install -g @ionic/cli

      - name: Build app
        run: ionic build

      - name: Capacitor sync
        run: npx cap sync

      - name: Build app bundle
        run: cd android && ./gradlew bundle

      - name: Extract Android signing key from env
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE }}" > android/release.jks.base64
          base64 -d android/release.jks.base64 > android/release.decrypted.jks

      - name: Sign dev build
        run: jarsigner -keystore android/release.decrypted.jks -storepass "${{ secrets.KEYSTORE_PASSWORD_ANDROID }}" -keypass "${{ secrets.KEYSTORE_PASSWORD_ANDROID }}" -signedjar ./android/app/build/outputs/bundle/release/app-release-signed.aab ./android/app/build/outputs/bundle/release/app-release.aab release

      - name: Upload release bundle
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: android/app/build/outputs/bundle/release/app-release-signed.aab
          retention-days: 1
