name: Deploy to staging
on:
  push:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Staging
    permissions:
      contents: read
      packages: write
      id-token: write
    name: Build and deploy to Azure

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set image tags and registry
        run: |
          echo "ACR_LOGIN_SERVER=${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io" >> $GITHUB_ENV
          echo "IMAGE_NAME=ingeniumuahubfrontend" >> $GITHUB_ENV
          echo "ACR_IMAGE=${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/ingeniumuahubfrontend:${{ github.sha }}" >> $GITHUB_ENV
          echo "ACR_LATEST=${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/ingeniumuahubfrontend:staging" >> $GITHUB_ENV
          echo "COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry via Azure CLI
        run: az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}

      - name: Build and push image to ACR
        uses: docker/build-push-action@v5
        with:
          build-args: ENVIRONMENT=staging
          push: true
          tags: |
            ${{ env.ACR_IMAGE }}
            ${{ env.ACR_LATEST }}

      - name: Deploy to Azure Container App from ACR
        run: |
          az containerapp update \
            --name ${{ vars.AZURE_CONTAINER_APP_NAME }} \
            --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
            --image ${{ env.ACR_IMAGE }} \
            --set-env-vars COMMIT_SHA=${{ env.COMMIT_SHA }}