on:
  push:
    branches: [ develop-sveltekit ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Staging
    permissions:
      contents: read
      packages: write
    name: Build container
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set lowercase owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Set image tag
        run: echo "IMAGE_TAG=ghcr.io/ingeniumua/ingeniumuahubfront:${{ github.sha }}" >> $GITHUB_ENV

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.OWNER_LC }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to registry
        uses: docker/build-push-action@v2
        with:
          build-args: ENVIRONMENT=staging
          push: true
          tags: |
            ${{ env.IMAGE_TAG }}
            ghcr.io/ingeniumua/ingeniumuahubfront:staging

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          containerAppName: ${{ vars.AZURE_CONTAINER_APP_NAME }}
          resourceGroup: ${{ vars.AZURE_RESOURCE_GROUP }}
          imageToDeploy: ${{ env.IMAGE_TAG }}
